<?php

use Dotenv\Dotenv;
// autoload.php @generated by Composer
$dotenv = Dotenv::createImmutable(dirname(__DIR__, 1));

$dotenv->load();

$server = $_ENV['DATABASE_SERVER'];
$username = $_ENV['DATABASE_USERNAME'];
$password = $_ENV['DATABASE_PASSWORD'];
$database = $_ENV['DATABASE_NAME'];

$con = mysqli_connect($server, $username, $password, $database);

if (mysqli_connect_error()) {
	exit('Failed to connect to MySQL: ' . mysqli_connect_error());
}
